---
title: "iteration_and_listcols"
author: "Yang Gao"
date: "11/9/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```


## Lists 
```{r}
l=
  list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, TRUE, FALSE),
  summary= summary(rnorm(1000, mean = 5, sd = 3))
  )

l[[2]]
l[["summary"]]
```

## Define functions
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

## list of normals
```{r}
list_norms = 
  list(
    a=rnorm(100, mean = 5, sd = 3),
    b=rnorm(100, mean = 10, sd = 3),
    c=rnorm(100, mean = 2, sd = 1),
    d=rnorm(100, mean = 12, sd = 0.5)
    
  )

mean_and_sd(list_norms[["a"]])

```


## for loops

```{r}
output = vector("list", length = 4)

output[[1]] = mean_and_sd(list_norms[[1]])



for( i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}

output
```

## using map instead

```{r}
output = map(list_norms, mean_and_sd)

output = map(list_norms, median)

output = map(list_norms, summary)


output = map_dbl(list_norms, median, .id = "input")
```

## List columns!!!
```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )


listcol_df %>% 
  filter(name =="a")

listcol_df %>%  pull(name)
listcol_df %>% pull(samp)

mean_and_sd(listcol_df$samp[[1]])

map(listcol_df$samp, mean_and_sd)

#could store the results as a new list column … !!!

listcol_df_new = 
  listcol_df %>% 
  mutate(summary = map(samp, mean_and_sd))

listcol_df_new

```

## Nested data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest %>% filter(name=="CentralPark_NY") %>% 
  pull(data)

unnest(weather_nest, cols = data)
```


```{r}
lm(tmax ~tmin, data = weather_nest$data[[3]])
lm(tmax ~tmin, data = weather_nest$data[[1]])
```


```{r}
weather_lm = function(df){
  
  lm(tmax~tmin, data = df)
}

weather_lm (weather_nest$data[[1]])

map(weather_nest$data, weather_lm)

weather_nest = weather_nest %>% 
  mutate(lm_result = map(data, weather_lm))
```

```{r}
read_page_reviews = function(url) {
  
  html = read_html(url)
  
  title = 
    html %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = 
    html %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  tibble(title, stars, text)
}
```


```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)



nap_df = 
  tibble(
    vec_urls = vec_urls
  )

nap_df %>% 
  mutate(reviews = map(vec_urls, read_page_reviews)) %>% 
  select(reviews)
 


```

```{r}
output = vector("list", 5)

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

dynamite_reviews = bind_rows(output)

dynamite_reviews = map_df(vec_urls, read_page_reviews)
```

