---
title: "writing_functions"
author: "Yang Gao"
date: "11/4/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

## Z-scores
```{r}
set.seed(1)

x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

#writing functions
z_scores = function(x) {
    z = (x - mean(x))/ sd(x)
  z}

z_scores (x = x_vec)
```


```{r}
z_scores(3)
```

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  z
}
```

## Multiple outputs
```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) < 3) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(output_df)
}

mean(x_vec)
sd(x_vec)
```

## Differnt sample sizes, means, sds
```{r}
sim_data = tibble(
    x = rnorm(30, mean = 2, sd = 3)
  )


sim_data %>% 
    summarize(
      mean= mean(x),
      sd = sd(x)
    )
```

lets write a function that simulates data, computes the mean and sd
```{r}
sim_mean_sd = function(n, mu, sigma){
  
  #check inputs
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )


  sim_data %>% 
    summarize(
      mean= mean(x),
      sd = sd(x)
    )
}

sim_mean_sd(30,4,3)
```






```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

write a fucntion that get reviews based on page url
```{r}
get_page_reviews = function(page_url) {
  
  page_html = read_html(page_url)
  
  review_titles = 
    page_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    page_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    page_html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()
  
  review = 
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  return(review)
}


base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

urls = str_c(base_url, 1:5)

bind_rows(
  get_page_reviews (urls[1]),
  get_page_reviews (urls[2]),
  get_page_reviews (urls[3]),
  get_page_reviews (urls[4]),
  get_page_reviews (urls[5])
)
```













